# Generated by Django 5.1.3 on 2024-12-01 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="recipe_images/"
                    ),
                ),
                ("instructions", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "grams"),
                            ("kg", "kilograms"),
                            ("ml", "milliliters"),
                            ("l", "liters"),
                            ("tsp", "teaspoon"),
                            ("tbsp", "tablespoon"),
                            ("cup", "cup"),
                            ("oz", "ounce"),
                            ("lb", "pound"),
                            ("pcs", "pieces"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
    ]
