# Generated by Django 5.1.3 on 2024-12-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_recipeingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "grams"),
                    ("kg", "kilograms"),
                    ("mg", "milligrams"),
                    ("ml", "milliliters"),
                    ("l", "liters"),
                    ("tsp", "teaspoon"),
                    ("tbsp", "tablespoon"),
                    ("cup", "cup"),
                    ("oz", "ounce"),
                    ("lb", "pound"),
                    ("pcs", "pieces"),
                    ("slice", "slice"),
                    ("pinch", "pinch"),
                    ("whole", "whole"),
                    ("stalk", "stalk"),
                    ("clove", "clove"),
                    ("can", "can"),
                    ("quart", "quart"),
                    ("pint", "pint"),
                ],
                max_length=10,
            ),
        ),
    ]
